### ISSUE TITLE
eagle-log无法sink到kafka，redis、es

### ISSUE THREAD

**Issue by w4lker** [luxiaoxun/eagle#8]
请问，是否要满足特定条件，才能调用sinkToRedis或者sinkLogToKafka。
因为我这边是自己根据logSchema的格式，自己写了一些日志进去，日志格式如下：
{"id":"1","type":"test","index":"eagle_log_1","timestamp":"2020-12-04T10:01:08.634+0800","@Timestamp":"1607064573799","ip":"172.19.88.67","message":"test","path":"c://test","fields":"aaa"}

timestamp和@Timestamp是动态的，其他字段都是硬编码写入到kafka，我调试代码，logprocess相关方法都会调用，但是sink日志到redis，kafka的代码都不会执行。

**Comment by w4lker** [comment]
提示这个错误：
[2020-12-04 17:10:45,413][INFO][org.apache.flink.runtime.taskmanager.Task]:955- redis-agg-log -> Sink: redis-sink (2/2) (122d404a7b477756920012ae2e65c92b) switched from RUNNING to FAILED.
java.lang.RuntimeException: Cannot instantiate tuple.
	at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.instantiateRaw(TupleSerializer.java:176)
	at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.copy(TupleSerializer.java:113)
	at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.copy(TupleSerializer.java:37)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:639)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:616)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:596)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:730)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:708)
	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:53)
	at com.alarm.eagle.redis.LogStatWindowFunction.process(LogStatWindowFunction.java:20)
	at com.alarm.eagle.redis.LogStatWindowFunction.process(LogStatWindowFunction.java:11)
	at org.apache.flink.streaming.runtime.operators.windowing.functions.InternalSingleValueProcessWindowFunction.process(InternalSingleValueProcessWindowFunction.java:53)
	at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.emitWindowContents(WindowOperator.java:549)
	at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.processElement(WindowOperator.java:406)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:173)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:151)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:128)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:69)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:311)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:187)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:487)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:470)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:707)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:532)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InstantiationException: com.alarm.eagle.redis.LogStatWindowResult
	at java.lang.Class.newInstance(Class.java:427)
	at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.instantiateRaw(TupleSerializer.java:173)
	... 24 more
Caused by: java.lang.NoSuchMethodException: com.alarm.eagle.redis.LogStatWindowResult.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 25 more

**Comment by luxiaoxun** [comment]
针对"index":"eagle_log_1" 这个日志，你有“解析规则”吗？你整个任务都报错了，debug看看

**Comment by w4lker** [comment]
规则是有解析的，我直接精简了规则，规则中只有一个logger输出信息，是没有问题的。所以是需要满足规则才会输出到redis吗？现在是报这个错误。
![image](https://user-images.githubusercontent.com/5175172/101154930-63dbaa00-3661-11eb-8c96-778b1eaedd4a.png)

**Comment by luxiaoxun** [comment]
"规则中只有一个logger输出信息" ，那就是没有处理后的日志输出。
我更新了下LogStatWindowFunction，修复了一个没有数据会抛出异常的问题。

**Comment by w4lker** [comment]
非常感谢更新，但是问题依然存在。也非常抱歉，因为我没有把错误代码贴全，“Could not forward element to next operator”不是根本原因，这个错误是由com.alarm.eagle.redis.LogStatWindowResult无法初始化造成的。请再帮忙看下，感激万分。
![image](https://user-images.githubusercontent.com/5175172/102337144-10f0e380-3fcd-11eb-9204-3bd7b4b1922d.png)

**Comment by w4lker** [comment]
把LogStatWindowResult的构造函数中的super类构造代码注释掉，程序便不会报错
![image](https://user-images.githubusercontent.com/5175172/102442461-6bd31b00-405f-11eb-84ba-13183f2e7aee.png)

**Comment by FantasticLiar** [comment]
> 非常感谢更新，但是问题依然存在。也非常抱歉，因为我没有把错误代码贴全，“Could not forward element to next operator”不是根本原因，这个错误是由com.alarm.eagle.redis.LogStatWindowResult无法初始化造成的。请再帮忙看下，感激万分。
> ![image](https://user-images.githubusercontent.com/5175172/102337144-10f0e380-3fcd-11eb-9204-3bd7b4b1922d.png)

我也遇到了这个问题，增加一个无参构造器就可以了
